### ISSUE TITLE
droppable example

### ISSUE THREAD

**Issue by jardakotesovec** [mzabriskie/react-draggable#13]
I am wondering how this draggable component actually can be used. I would think that usual use case is to drag & drop. But I struggle to see how I could use it for drag&drop. 

Is anyone here using it for drag&drop? It would be very helpful to see example.

Thank you!

**Comment by mwean** [comment]
Does this still work? I tried adding `onDrop`, `onDragEnter`, and `onDragOver` handlers to a div, and they're not getting triggered. I assume it's because we're just moving the element with CSS. Is there any other way to handle dropping?
